version: '3'
services:
    postgres:
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_USER: strapi
            POSTGRES_PASSWORD: strapi
            POSTGRES_DB: strapidb
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
